import { Spline_Sans_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import NavCard from "@/components/NavCard";

const splineMono = Spline_Sans_Mono({
  variable: "--font-spline-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${splineMono.variable} antialiased`}>
        <div className="hidden fixed top-0 left-0 lg:grid grid-rows-5 w-1/5 h-screen gap-2 max-h-screen py-2">
          <Link href="/about">
            <NavCard Text="About" />
          </Link>
          <Link href="/gallery">
            <NavCard Text="Gallery" />
          </Link>
          <Link href="/Events">
            <NavCard Text="Events" />
          </Link>
          <Link href="/Contact">
            <NavCard Text="Contact" />
          </Link>
          <Link href="/Contact">
            <NavCard Text="Contact" />
          </Link>
        </div>
        <div className="absolute top-0 right-0 w-full lg:w-4/5 p-2 overflow-y-auto h-[200vh] lg:h-screen grid  gap-2 grid-cols-1 lg:grid-cols-2 grid-rows-10">
          <div className="row-span-1 lg:row-span-2 col-span-1 w-full h-full border-t-4 border-[#fff] p-2 text-[2rem]">
            "rsgbsergbvs"
          </div>
          <div className="row-span-1 lg:row-span-2  col-span-1 w-full h-full border-t-4 border-[#fff] p-2 text-[2rem]">
            "rsgbsergbvs"
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
