import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#310000] text-white`}
      >
        <div className="flex gap-2">
          <div className="hidden lg:grid w-1/5 h-screen gap-2">
            <div className="row-span-1 bg-black w-full">dvfgsd</div>
            <div className="row-span-1 w-full bg-black">dvfgsd</div>
            <div className="row-span-1 w-full bg-black">dvfgsd</div>
            <div className="row-span-1 w-full bg-black">dvfgsd</div>
          </div>
          <div className="w-full lg:w-4/5">
            <div className="hidden lg:flex gap-2 mb-2">
              <div className="w-1/2 h-20 bg-black">sdvgsdv</div>
              <div className="w-1/2 h-20 bg-black">sdvgsdv</div>
            </div>
            <div className="min-h-20 bg-black">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
